
spring:
  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/basicreview
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail-username}
    password: ${mail-password}
    from: basic-review@proejct.com
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls.required: true
          starttls.enable: true

jwt:
  secret:
    key: ${jwt-secret-key}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: ${s3-bucket-name}
    region:
      static: ap-northeast-2
    stack:
      auto: false
---

spring:
  config:
    activate:
      on-profile: test
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:testdb;MODE=MySQL;
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail-username}
    password: ${mail-password}
    from: basic-review@proejct.com
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls.required: true
          starttls.enable: true

jwt:
  secret:
    key: bmV3c2ZlZWQtand0LXNlY3JldC1rZXluZXdzZmVlZC1qd3Qtc2VjcmV0LWtleQ==

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: ${s3-bucket-name}
    region:
      static: ap-northeast-2
    stack:
      auto: false